name: Atlas
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  atlas:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Generate atlas
      run: montage *.png *.gif -background transparent -resize 512x512 -gravity northwest -extent 512x512 atlas.png
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Atlas
        path: atlas.png
